"""create tables

Revision ID: 546f84e030c3
Revises: 
Create Date: 2024-05-14 19:13:33.327817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546f84e030c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_created_at'), 'chat', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.create_table('form_submission',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submission_chat_id'), 'form_submission', ['chat_id'], unique=False)
    op.create_index(op.f('ix_form_submission_created_at'), 'form_submission', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_submission_email'), 'form_submission', ['email'], unique=False)
    op.create_index(op.f('ix_form_submission_id'), 'form_submission', ['id'], unique=False)
    op.create_index(op.f('ix_form_submission_name'), 'form_submission', ['name'], unique=False)
    op.create_index(op.f('ix_form_submission_phone_number'), 'form_submission', ['phone_number'], unique=False)
    op.create_index(op.f('ix_form_submission_status'), 'form_submission', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submission_status'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_phone_number'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_name'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_id'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_email'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_created_at'), table_name='form_submission')
    op.drop_index(op.f('ix_form_submission_chat_id'), table_name='form_submission')
    op.drop_table('form_submission')
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_index(op.f('ix_chat_created_at'), table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
